src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ReclamationRepository::class)
 */
class Reclamation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $date_reclamtion;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reclamations")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Evenement::class, inversedBy="reclamations")
     */
    private $evenement;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $etat;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateReclamtion(): ?\DateTimeInterface
    {
        return $this->date_reclamtion;
    }

    public function setDateReclamtion(?\DateTimeInterface $date_reclamtion): self
    {
        $this->date_reclamtion = $date_reclamtion;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEvenement(): ?Evenement
    {
        return $this->evenement;
    }

    public function setEvenement(?Evenement $evenement): self
    {
        $this->evenement = $evenement;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description',TextareaType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Entity\Notification;
use App\Entity\Reclamation;
use App\Entity\ReclamationFacc;
use App\Entity\User;
use App\Form\ReclamationType;
use App\Repository\ReclamationRepository;
use Knp\Component\Pager\PaginatorInterface;
use phpDocumentor\Reflection\Type;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Mercure\PublisherInterface;
use Symfony\Component\Mercure\Update;

class ReclamationController extends AbstractController
{
    /**
     * @Route("/reclamation", name="reclamation", methods={"GET"})
     */
    public function index(ReclamationRepository $reclamationRepository,\Symfony\Component\HttpFoundation\Request $request , PaginatorInterface $paginator): Response
    {
        $reclamation =$reclamationRepository->findAll();
        $paginat = $paginator->paginate(
            $reclamation ,
            $request->query->getInt('page',1),
            3
        );
        return $this->render('reclamation/index.html.twig', [
            'reclamations' => $paginat,
        ]);
    }


    /**
     * @Route("/{id}/newreclamation", name="newreclamation" )
     */
    public function new(Request $request , $id ,\Swift_Mailer $mailer , PublisherInterface $publisher , SessionInterface $session): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $reclamation)
            ->add('type',ChoiceType::class ,
                [
                    'choices' => [
                        'Insatisfaction liée au lieu' => 'Insatisfaction liée au lieu',
                        'Mauvaise organisation' => 'Mauvaise organisation',
                        'horaires de début non respecté' => 'horaires de début non respecté',
                        'other' => 'other'
                    ],
                    'expanded' => true
                ])
            ->add("send",SubmitType::class);

        $form->handleRequest($request);
        $evenemenetRep = $this->getDoctrine()->getRepository(Evenement::class);
        $evenemenet = $evenemenetRep->find($id);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRep = $this->getDoctrine()->getRepository(User::class);
            $user = $userRep->find($session->get('user'));
            $reclamation->setEvenement($evenemenet);
            $reclamation->setUser($user);
            $reclamation->setDateReclamtion(new \DateTime());
            if ($reclamation->getType() == 'other') {
                if (empty($reclamation->getDescription())) {
                    return $this->render('reclamation/new.html.twig', [
                        'reclamation' => $reclamation,
                        'nott' => 'not empty',
                        'form' => $form->createView(),
                    ]);
                }

            }

            $email=$user->getEmail();
            $message = (new \Swift_Message('Hello Email'))
                ->setFrom('projetpidev992@gmail.com')
                ->setTo($email)
                ->setBody(
                    $this->renderView(
                    // templates/emails/registration.html.twig
                        'reclamation/sendmail.html.twig',
                        ['reclamation' => $reclamation ]
                    ),
                    'text/html'
                );
            $mailer->send($message);


            $reclamation->setEtat("attente");

            $entityManager = $this->getDoctrine()->getManager();
            $notif = new Notification() ;
            $notif->setReclamation($reclamation) ;

            $entityManager->persist($reclamation);
            $entityManager->persist($notif);
            $entityManager->flush();


            // Notification part
            $update = new Update(
                'http://monsite.com/new',
                json_encode(['nom' => $reclamation->getUser()->getNom() , 'id' => $reclamation->getId() , 'evenement'=> $reclamation->getEvenement()->getNom() , 'date' => $reclamation->getDateReclamtion() , 'type' => 'evenement'])
            );

            // The Publisher service is an invokable object
            $publisher($update);

            return $this->redirectToRoute('lister');

        }

        return $this->render('reclamation/new.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/notificationsReclamation", name="notificationsReclamation")
     */
    public function notificationsReclamation()
    {
        $notif = $this->getDoctrine()->getRepository(Notification::class);
        $data = $notif->findAll();
        $res = [];

        foreach ($data as $r)
        {
            $evenement = $r->getReclamation() ;
            if ($evenement != null)
            {
                $evenement = $r->getReclamation()->getEvenement()->getNom();
                $nom = $r->getReclamation()->getUser()->getNom();
                $id = $r->getReclamation()->getId();
                $date = $r->getReclamation()->getDateReclamtion();
                $notif = ['nom' => $nom , 'id' => $id , 'evenement' => $evenement , 'date' => $date , 'type' => 'evenement' ] ;
            }else
            {

                 $fa = $r->getReclamationFamille()->getFacceuil()->getNom();
                 $nom = $r->getReclamationFamille()->getUser()->getNom();
                 $id = $r->getReclamationFamille()->getId();
                 $date = $r->getReclamationFamille()->getDateReclamation();
                 $notif = ['nom' => $nom , 'id' => $id , 'facceuil' => $fa , 'date' => $date , 'type' => 'facceuil' ] ;
            }

            array_push($res,$notif);
        }


        $response = new Response();

        $response->setContent(json_encode([['Notifications' => $res],['nbr' => count($res)] ]));

        $response->headers->set('Content-Type', 'application/json');
        $response->headers->set('Access-Control-Allow-Origin', '*');


    return $response;
    }

    /**
     * @Route("/{id}/showreclamation", name="showreclamation", methods={"GET"})
     */
    public function show(Reclamation $reclamation): Response
    {
        return $this->render('reclamation/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }

    /**
     * @Route("/{id}/editreclamation", name="editreclamation", methods={"GET","POST"})
     */
    public function edit(Request $request, Reclamation $reclamation): Response
    {
        $form = $this->createForm(ReclamationType::class, $reclamation)
            ->add("modifier",SubmitType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reclamation');
        }

        return $this->render('reclamation/edit.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/deletereclamation", name="deletereclamation")
     */
    public function delete(Request $request, $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $reclamationRepository = $this->getDoctrine()->getRepository(Reclamation::class);
        $reclamation = $reclamationRepository->find($id);
        $entityManager->remove($reclamation);
        $entityManager->flush();
        return $this->redirectToRoute('reclamation');
    }

    public function getStatDate($data)
    {
        $res = array(0,0,0,0,0,0,0,0,0,0,0,0) ;
        foreach ($data as $r)
        {

            $index = $r->getDateReclamtion()->format('m') ;
            if ((int)$index >= 10)
                $index = $r->getDateReclamtion()->format('m') - 1 ;
            else
                $index = $r->getDateReclamtion()->format('m')[1] - 1 ;
            $res[$index]++ ;
        }

        return $res ;
    }

    /**
     * @Route("/stat", name="stat", methods={"GET"})
     */
    public function stat(ReclamationRepository $reclamationRepository)
    {
        $data=$reclamationRepository->findAll();
        $res = $this->getStatDate($data) ;
        $etatRef = 0 ;
        $etatAcc = 0 ;
        $etatAtt = 0 ;
        $type1 = 0 ;
        $type2= 0 ;
        $type3= 0 ;
        $type4= 0 ;
        foreach ($data as $t)
        {
            $type=$t->getType();
            if ($type=="Insatisfaction liée au lieu"){
                $type1++;
            }
            elseif ($type=="Mauvaise organisation"){
                $type2++;
            }
            elseif ($type=="horaires de début non respecté"){
                $type3++;
            }
            elseif ($type=="other"){
                $type4++;
            }

            if ($t->getEtat() == 'attente')
            {
                $etatAtt++ ;
            } elseif ($t->getEtat() == 'accepter')
            {
                $etatAcc++ ;
            } elseif ($t->getEtat() == 'refuser')
            {
                $etatRef++ ;
            }

        }
        $reclamation= $reclamationRepository->countbydate();
        $dates = [];
        $reclamationcount = [];

        foreach ($reclamation as $reclame){
            $dates[]= $reclame['date_reclamtion'];
            $reclamationcount[]=$reclame['count'];

    }
        $choice=['Insatisfaction liée au lieu','Mauvaise organisation',
            'horaires de début non respecté','other'];

        return $this->render('/reclamation/stat.html.twig' ,

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('deletereclamation', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reclamation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reclamation/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}  Edit reclamation {% endblock %}

{% block content %}

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block"> <img src="{{ asset('back/img/tt.jpg') }}" width="400" height="530"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Update Reclamation</h1>
                            </div>
                            <div class="form-group">
                                {{ form_start(form) }}
                                {{ form_widget(form.description , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'description'}} ) }}
                                {{ form_errors(form.description) }}
                                <div class="form-group">
                                    {{ form_widget(form.date_reclamtion , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'description'}} ) }}
                                    {{ form_errors(form.date_reclamtion) }}
                                </div>
                            </div>
                            <div class="form-group">
                                {{ form_widget(form.user , {'attr': {'class': 'form-control form-control-user' , }} ) }}
                                {{ form_errors(form.user) }}
                            </div>
                            <div class="form-group">
                                <div class=" mb-3 mb-sm-0">
                                    {{ form_widget(form.evenement , {'attr': {'class': 'form-control form-control-user' }} ) }}
                                    {{ form_errors(form.evenement) }}
                                </div>
                            </div>
                            <div class="form-group">
                                {{ form_widget(form.user , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Age'}} ) }}
                                {{ form_errors(form.user) }}

                            </div>
                            <div class="form-group">
                                {{ form_widget(form.modifier , {'attr': {'class': 'form-control form-control-user btn-info' }} ) }}

                            </div>
                            <hr>
                            {{ form_end(form) }}
                            <hr>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

templates/reclamation/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}  Reclamation {% endblock %}

{% block content %}
<h1 style="text-align: center">Liste des Reclamations </h1>


<body id="page-top">
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-body">

        <input style="margin-bottom: 10px" class="form-control" id="myInput" type="text" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
        <div class="table-responsive">
            <table class="table table-bordered"  width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Description</th>
                    <th>Date_reclamtion</th>
                    <th>User</th>
                    <th>Evenement</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody id="hi">
                {% for reclamation in reclamations %}
                    <tr>
                        <td>{{ reclamation.id }}</td>
                        <td>{{ reclamation.description }}</td>
                        <td>{{ reclamation.dateReclamtion ? reclamation.dateReclamtion|date('Y-m-d') : '' }}</td>
                        <td>{{ reclamation.user }}</td>
                        <td>{{ reclamation.evenement }}</td>
                        <td><a href="{{ url('deletereclamation' , {id : reclamation.id} ) }}"> <img src="{{ asset('back/img/icon-delete.jpg') }}" alt="delete" width="50px" height="50px" >  </a></td>

                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div style="margin-left: 1400px">
                {{ knp_pagination_render(reclamations) }}
            </div>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function(){
        $("#myInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#hi tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>


{% endblock %}

templates/reclamation/mailreclamation.html.twig
<!doctype html>
<html lang="en-US">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <meta name="description" >
    <style type="text/css">
        a:hover {text-decoration: underline !important;}
    </style>
</head>

<body marginheight="0" topmargin="0" marginwidth="0" style="margin: 0px; background-color: #f2f3f8;" leftmargin="0">
<!--100% body table-->
<table cellspacing="0" border="0" cellpadding="0" width="100%" bgcolor="#f2f3f8"
       style="@import url(https://fonts.googleapis.com/css?family=Rubik:300,400,500,700|Open+Sans:300,400,600,700);
       font-family: 'Open Sans', sans-serif;">
    <tr>
        <td>
            <table style="background-color: #f2f3f8; max-width:670px;  margin:0 auto;" width="100%" border="0"
                   align="center" cellpadding="0" cellspacing="0">
                <tr>
                    <td style="height:80px;">&nbsp;</td>
                </tr>
                <tr>
                    <td style="text-align:center;">
                        <a href="{{asset('front')}}" title="logo" target="_blank">
                            <img width="40" height="53" src="i.ibb.co/LncjHx3/logo.png">
                        </a>
                    </td>
                </tr>
                <tr>
                    <td style="height:20px;">&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <table width="95%" border="0" align="center" cellpadding="0" cellspacing="0"
                               style="max-width:670px;background:#fff; border-radius:3px; text-align:center;
                               -webkit-box-shadow:0 6px 18px 0
                               rgba(0,0,0,.06);-moz-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);box-shadow:0 6px 18px 0
                               rgba(0,0,0,.06);">
                            <tr>
                                <td style="height:40px;">&nbsp;</td>
                            </tr>
                            <tr>
                                <td style="padding:0 35px;">
                                    <h1 style="color:#1e1e2d; font-weight:500; margin:0;font-size:32px;
                                    font-family:'Rubik',sans-serif;"> Votre reclamation a été consulter</h1>
                                    <span
                                            style="display:inline-block; vertical-align:middle; margin:29px 0 26px;
                                            border-bottom:1px solid #cecece; width:100px;"></span>
                                    <p style="color:#455056; font-size:15px;line-height:24px; margin:0;">
                                        Bonjour,Mr/Mme {{ reclamation.user }}<br>
                                        Votre reclamation sur l'evenement " {{ reclamation.evenement }}"<br>
                                        de type : {{ reclamation.type  }}<br>
                                        {% if reclamation.description is not empty %}
                                            avec la descrition suivent : {{ reclamation.description }}<br>
                                        {% endif %}
                                        a été {{ reclamation.etat }}.
                                    </p>

                                </td>
                            </tr>

                        </table>
                    </td>
                <tr>
                    <td style="height:20px;">&nbsp;</td>
                </tr>

                <tr>
                    <td style="height:80px;">&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<!--/100% body table-->
</body>

</html>

templates/reclamation/show.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}  Afficher Reclamation {% endblock %}

{% block content %}


<body id="page-top">
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ reclamation.id }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ reclamation.description }}</td>
                </tr>
                <tr>
                    <th>Date_reclamation</th>
                    <td>{{ reclamation.datereclamtion ? reclamation.datereclamtion|date('Y-m-d') : '' }}</td>
                </tr>
                <tr>
                    <th>User</th>
                    <td>{{ reclamation.user }}</td>
                </tr>
                <tr>
                    <th>Evenement</th>
                    <td>{{ reclamation.evenement }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->




{% endblock %}

templates/reclamation/vu.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}  Reclamation {% endblock %}

{% block content %}

<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-xl-6 col-md-12">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-4 bg-c-lite-green user-profile">
                            <div class="card-block text-center text-white">
                                <div class="m-b-25"> <img src="https://weezevent.com/wp-content/uploads/2018/06/organiser-evenement-professionnel-original-weezevent.jpg"
                                                          class="img-radius" alt="User-Profile-Image"
                                    width="120px" height="120px"> </div>

                                <p>{{ reclamation.evenement }}</p> <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Reclamation</h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">User</p>
                                        <h6 class="text-muted f-w-400">{{ reclamation.user }}</h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Date</p>
                                        <h6 class="text-muted f-w-400">{{ reclamation.dateReclamtion|date('Y-m-d') }}</h6>
                                    </div>
                                </div>
                                <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600"></h6>

                                    <div>
                                        <p class="m-b-10 f-w-600" style="text-align: center">Type :</p>
                                        <h6 class="text-muted f-w-400" style="text-align: center">{{ reclamation.type }}</h6>
                                    </div>
                               {% if reclamation.type == "other" %}
                                    <div >
                                        <p class="m-b-10 f-w-600" style="text-align: center">Description</p>
                                        <h6 class="text-muted f-w-400" style="text-align: center">{{ reclamation.description }}</h6>
                                    </div>
                                {% endif %}
                                <div class="row" style="margin-top: 20px; ">
                                    <a href="{{ url('gerer', {'id': reclamation.id , 'etat': "accepter"}) }}">
                                        <button class="btn btn-info" style="width: 120px ;
                                        margin-right: 10px ;margin-left: 15px" >Accepter</button>
                                    </a>
                                    <a href="{{ url('gerer', {'id': reclamation.id , 'etat': "refuser"}) }}">
                                        <button class="btn btn-danger" style="width: 120px;" >Refuser</button>
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    body {
        background-color: #f9f9fa
    }

    .padding {
        padding: 3rem !important
    }

    .user-card-full {
        overflow: hidden
    }

    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        border: none;
        margin-bottom: 30px
    }

    .m-r-0 {
        margin-right: 0px
    }

    .m-l-0 {
        margin-left: 0px
    }

    .user-card-full .user-profile {
        border-radius: 5px 0 0 5px
    }

    .bg-c-lite-green {
        background: -webkit-gradient(linear, left top, right top, from(#f29263), to(#ee5a6f));
        background: linear-gradient(to right, #ee5a6f, #f29263)
    }

    .user-profile {
        padding: 20px 0
    }

    .card-block {
        padding: 1.25rem
    }

    .m-b-25 {
        margin-bottom: 25px
    }

    .img-radius {
        border-radius: 5px
    }

    h6 {
        font-size: 14px
    }

    .card .card-block p {
        line-height: 25px
    }

    @media only screen and (min-width: 1400px) {
        p {
            font-size: 14px
        }
    }

    .card-block {
        padding: 1.25rem
    }

    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }

    .m-b-20 {
        margin-bottom: 20px
    }

    .p-b-5 {
        padding-bottom: 5px !important
    }

    .card .card-block p {
        line-height: 25px
    }

    .m-b-10 {
        margin-bottom: 10px
    }

    .text-muted {
        color: #919aa3 !important
    }

    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }

    .f-w-600 {
        font-weight: 600
    }

    .m-b-20 {
        margin-bottom: 20px
    }

    .m-t-40 {
        margin-top: 20px
    }

    .p-b-5 {
        padding-bottom: 5px !important
    }

    .m-b-10 {
        margin-bottom: 10px
    }

    .m-t-40 {
        margin-top: 20px
    }

    .user-card-full .social-link li {
        display: inline-block
    }

    .user-card-full .social-link li a {
        font-size: 20px;
        margin: 0 10px 0 0;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out
    }
</style>



{% endblock %}