src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tourist;

    /**
     * @ORM\ManyToOne(targetEntity=Evenement::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $evenement;

    /**
     * @ORM\ManyToOne(targetEntity=Offre::class, inversedBy="reservations")
     */
    private $offre;

    /**
     * @ORM\Column(type="date")
     */
    private $date_reservation;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank
     */
    private $tarif;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTourist(): ?User
    {
        return $this->tourist;
    }

    public function setTourist(?User $tourist): self
    {
        $this->tourist = $tourist;

        return $this;
    }

    public function getEvenement(): ?Evenement
    {
        return $this->evenement;
    }

    public function setEvenement(?Evenement $evenement): self
    {
        $this->evenement = $evenement;

        return $this;
    }

    public function getOffre(): ?Offre
    {
        return $this->offre;
    }

    public function setOffre(?Offre $offre): self
    {
        $this->offre = $offre;

        return $this;
    }

    public function getDateReservation(): ?\DateTimeInterface
    {
        return $this->date_reservation;
    }

    public function setDateReservation(?\DateTimeInterface $date_reservation): self
    {
        $this->date_reservation = $date_reservation;

        return $this;
    }

    public function getTarif(): ?float
    {
        return $this->tarif;
    }

    public function setTarif(?float $tarif): self
    {
        $this->tarif = $tarif;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Entity\Reservation;
use App\Entity\User;
use App\Form\ReservationType;
use App\Repository\EvenementRepository;
use App\Repository\OffreRepository;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ReservationController extends AbstractController
{
    /**
     * @Route("/reservations", name="reservations", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/newreservation", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation)
            ->add('ajouter',SubmitType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservations');
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/reservation/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/editreservation", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation)->add('modifier', SubmitType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservations');
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/deletereservation", name="reservation_delete")
     */
    public function delete(Request $request, $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $reservationRepository = $this->getDoctrine()->getRepository(Reservation::class);
        $reservation = $reservationRepository->find($id);
        $entityManager->remove($reservation);
        $entityManager->flush();
        return $this->redirectToRoute('reservations');
    }

    /**
     * @Route("/frontReservations", name="frontReservations", methods={"GET"})
     */
    public function frontReservation(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/frontreservations.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}/newreservationfront", name="new_reservation", methods={"GET","POST"})
     */
    public function newf(Request $request , EvenementRepository $evenementRepository , $id): Response
    {
        $reservation = new Reservation();
        $entityManager = $this->getDoctrine()->getManager();
        $event = $evenementRepository->find($id);
        $userrep=$this->getDoctrine()->getRepository(User::class);
        $user=$userrep->find($this->getUser()->getId());
        $tarif = $event->getPrix();
        $reservation->setEvenement($event);
        $reservation->setTourist($user);
        $reservation->setTarif($tarif);
        $reservation->setDateReservation(new \DateTime());
        $form = $this->createForm(ReservationType::class, $reservation)
            ->add('ajouter',SubmitType::class);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $event->setNbrPlaces($event->getNbrPlaces() - 1);
            $entityManager->persist($reservation);
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('frontmesReservations');
        }

        return $this->render('reservation/frontreservation.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
            'event' => $evenementRepository->find($id),
        ]);
    }

    /**
     * @Route("/{id}/newreservationofront", name="new_reservationo", methods={"GET","POST"})
     */
    public function newfn(Request $request , OffreRepository $offreRepository , $id , EvenementRepository $evenementRepository): Response
    {
        $reservation = new Reservation();
        $entityManager = $this->getDoctrine()->getManager();
        $offre = $offreRepository->find($id);
        $event = $offre->getEvenement();
        $userrep=$this->getDoctrine()->getRepository(User::class);
        $user=$userrep->find($this->getUser()->getId());
        $tarif = ($event->getPrix() / 100 ) * $offre->getPourcentage();
        $reservation->setEvenement($event);
        $reservation->setOffre($offre);
        $reservation->setTourist($user);
        $reservation->setDateReservation(new \DateTime());
        $reservation->setTarif($tarif);
        $form = $this->createForm(ReservationType::class, $reservation)
            ->add('ajouter',SubmitType::class);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $event = $offreRepository->find($id)->getEvenement();
            $event->setNbrPlaces($event->getNbrPlaces() - 1);
            $entityManager->persist($reservation);
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('frontmesReservations');
        }

        return $this->render('reservation/frontreservationo.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
            'offre' => $offreRepository->find($id),
        ]);
    }

    /**
     * @Route("/{id}/editreservationfront", name="edit_reservation", methods={"GET","POST"})
     */
    public function editf(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation)->add('modifier', SubmitType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservations');
        }

        return $this->render('reservation/editfront.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/deletereservationfront", name="delete_reservation")
     */
    public function deletef(Request $request, $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $reservationRepository = $this->getDoctrine()->getRepository(Reservation::class);
        $reservation = $reservationRepository->find($id);
        $entityManager->remove($reservation);
        $entityManager->flush();
        $this->get('session')->getFlashBag()->add('notice','Reservation Supprimé');
        return $this->redirectToRoute('frontmesReservations');
    }

    /**
     * @Route("/frontmesReservations", name="frontmesReservations", methods={"GET"})
     */
    public function frontmesReservation(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/frontmesreservations.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }


}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}  Modifier Reservation {% endblock %}

{% block content %}

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block"> <img src="{{ asset('back/img/tt.jpg') }}" width="400" height="530"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Modifier Reservation</h1>
                            </div>
                                <div class="form-group">
                                    {{ form_start(form) }}
                                    {{ form_widget(form.tourist , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Tourist'}} ) }}
                                    {{ form_errors(form.tourist) }}
                                </div>
                                <div class="form-group">
                                    {{ form_widget(form.evenement , {'attr': {'class': ' form-select-lg form-control form-control-user' , 'placeholder' : 'Event'}} ) }}
                                    {{ form_errors(form.evenement) }}
                                </div>
                                <div class="form-group">
                                    {{ form_widget(form.offre , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Offre'}} ) }}
                                    {{ form_errors(form.offre) }}
                                </div>
                                <div class="form-group">
                                    {{ form_widget(form.date_reservation , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Date Reservation'}} ) }}
                                    {{ form_errors(form.date_reservation) }}
                                </div>
                                <div class="form-group">
                                    {{ form_widget(form.tarif, {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Tarif'}} ) }}
                                    {{ form_errors(form.tarif) }}
                                </div>
                            <div class="form-group">
                                {{ form_widget(form.modifier , {'attr': {'class': 'form-control form-control-user btn-info' , 'placeholder' : 'Modifier'}} ) }}
                                {{ form_end(form) }}
                            </div>
                            <div align="right">
                                <a href="{{ path('offres') }}">Retourner vers Offres</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

templates/reservation/editfront.html.twig
{% extends 'baseFront.html.twig' %}

{% block change %}

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block"> <img src="{{ asset('back/img/tt.jpg') }}" width="400" height="530"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Modifier Reservation</h1>
                            </div>
                            <div class="form-group">
                                {{ form_start(form) }}
                                {{ form_widget(form.tourist , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Tourist'}} ) }}
                                {{ form_errors(form.tourist) }}
                            </div>
                            <div class="form-group">
                                {{ form_widget(form.evenement , {'attr': {'class': ' form-select-lg form-control form-control-user' , 'placeholder' : 'Event'}} ) }}
                                {{ form_errors(form.evenement) }}
                            </div>
                            <div class="form-group">
                                {{ form_widget(form.offre , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Offre'}} ) }}
                                {{ form_errors(form.offre) }}
                            </div>
                            <div class="form-group">
                                {{ form_widget(form.date_reservation , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Date Reservation'}} ) }}
                                {{ form_errors(form.date_reservation) }}
                            </div>
                            <div class="form-group">
                                {{ form_widget(form.tarif, {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Tarif'}} ) }}
                                {{ form_errors(form.tarif) }}
                            </div>
                            <div class="form-group">
                                {{ form_widget(form.modifier , {'attr': {'class': 'form-control form-control-user btn-info' , 'placeholder' : 'Modifier'}} ) }}
                                {{ form_end(form) }}
                            </div>
                            <div align="right">
                                <a href="{{ path('frontOffres') }}">Retourner vers Reservations</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

templates/reservation/frontmesreservations.html.twig
{% extends 'baseFront.html.twig' %}
{% block search %}
    <style>
        .book_button
        {
            background: #31124b;
            margin-top: 39px;
            margin-bottom: -5px;
            -webkit-transition: all 200ms ease;
            -moz-transition: all 200ms ease;
            -ms-transition: all 200ms ease;
            -o-transition: all 200ms ease;
            transition: all 200ms ease;
        }
    </style>
    <div class="search">
        <div class="container fill_height">
            <div class="row fill_height">
                <div class="col fill_height">
                    <div class="search_tabs_container">
                        <div class="search_tabs d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-lg-between justify-content-start">
                            <div class="search_tab d-flex flex-row align-items-center justify-content-lg-center justify-content-start"><img src="{{asset('front/images/suitcase.png')}}" alt=""><span>Hotels</span></div>
                            <div class="search_tab d-flex flex-row align-items-center justify-content-lg-center justify-content-start"><img src="{{asset('front/images/bus.png')}}" alt="">Familles Acceuils</div>
                            <div class="search_tab d-flex flex-row align-items-center justify-content-lg-center justify-content-start"><img src="{{asset('front/images/departure.png')}}" alt="">Guides</div>
                            <div class="search_tab d-flex flex-row align-items-center justify-content-lg-center justify-content-start"><img src="{{asset('front/images/island.png')}}" alt="">Vendeurs</div>
                            <div class="search_tab active d-flex flex-row align-items-center justify-content-lg-center justify-content-start"><img src="{{asset('front/images/cruise.png')}}" alt="">Evenements</div>
                            <div class="search_tab d-flex flex-row align-items-center justify-content-lg-center justify-content-start"><img src="{{asset('front/images/diving.png')}}" alt="">Offres</div>
                        </div>
                    </div>
                    <div class="search_panel active">
                        <form action="#" id="search_form_1" class="search_panel_content d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-lg-between justify-content-start">
                            <div class="search_item">
                                <div>Destination</div>
                                <input type="text" class="destination search_input" required="required">
                            </div>
                            <div class="search_item">
                                <div>Date Debut</div>
                                <input type="text" class="check_in search_input" placeholder="YYYY-MM-DD">
                            </div>
                            <div class="search_item">
                                <div>Date Fin</div>
                                <input type="text" class="check_out search_input" placeholder="YYYY-MM-DD">
                            </div>
                            <div class="search_item">
                                <div>Nombre Places</div>
                                <select name="adults" id="adults_1" class="dropdown_item_select search_input">
                                    <option>01</option>
                                    <option>02</option>
                                    <option>03</option>
                                    <option>04</option>
                                    <option>05</option>
                                    <option>01</option>
                                    <option>02</option>
                                    <option>03</option>
                                    <option>01</option>
                                    <option>02</option>
                                    <option>03</option>
                                </select>
                            </div>
                            <button class="button search_button">Rechercher<span></span><span></span><span></span></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block change %}
    <div class="col-lg-14">
    <br>
    <div class="offers_price" style="padding-left: 650px">Mes Resrvations</div>
    {% for v in reservations %}
        <div class="offers_grid">
            <div class="offers_item rating_3">
                <div class="row">
                    <div class="col-lg-1 temp_col"></div>
                    <div class="col-lg-3 col-1680-4">
                    </div>
                    <div class="col-lg-8">
                        <div class="offers_content">
                            <div class="offers_price">{{ v.tourist}}</div>
                            <h3 class="mt-3">Nom Evenement: {{ v.evenement }}</h3>
                            {% if v.offre != null %}
                            <h3 class="mt-3">Nom Offre: {{ v.offre }}</h3>
                            {% endif %}
                            <h3 class="mt-3">Date Reservation: {{ v.dateReservation ? v.dateReservation|date('d-m-Y') : '' }}</h3>
                            <h3 class="mt-3">Prix: {{ v.tarif }}Dt</h3>
                            <div class="row" >
                                <div style="padding-left: 100px">     <a href="{{ url('delete_reservation'  , {'id' : v.id} )}}"><button type="button" class="button book_button btn-danger" name="button" style="width: 150px"> Supprimer<span></span><span></span><span></span></button> </a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        <br>
    {% endfor %}
{% endblock %}

templates/reservation/frontreservations.html.twig
{% extends 'baseFront.html.twig' %}
{% block change %}
    <div align="center" height="100" weight="100">     <a href="{{ url('new_reservation')}}"><button type="button" class="btn btn-info mb-4" name="button"> Ajouter Reservation </button> </a></div>
    <!-- Offers Item -->
    {% for v in reservations %}
        <div class="offers_item rating_3">
            <div class="row mt-5">
                <div class="col-lg-1 temp_col"></div>
                <div class="col-lg-3 col-1680-4">



                </div>
                <div class="col-lg-8">
                    <div class="offers_content">
                        <div class="mr-5 " align="right">
                            <a href="{{ url('frontReservations')}}"><img src="{{ asset('front/images/alert.png')}}" alt="alert" height="50" weight="50"></a>
                        </div>
                        <h3> {{ v.tourist}}</h3>
                        <div class="offers_price">{{ v.evenement}}<span>available rooms</span></div>
                        <div class="offers_price">{{ v.offre}}<span>available rooms</span></div>
                        <div class="offers_price">{{ v.dateReservation ? v.dateReservation|date('Y-m-d') : '' }}<span>available rooms</span></div>
                        <div class="offers_price">{{ v.tarif}}<span>available rooms</span></div>

                        <div class="rating_r rating_r_3 offers_rating" data-rating="3">
                            <i></i>
                            <i></i>
                            <i></i>
                            <i></i>
                            <i></i>
                        </div>

                        <div class="offers_icons">
                            <ul class="offers_icons_list">
                                <li class="offers_icons_item"><img src="{{ asset('front/images/post.png') }}" alt=""></li>
                                <li class="offers_icons_item"><img src="{{ asset('front/images/compass.png') }}" alt=""></li>
                                <li class="offers_icons_item"><img src="{{ asset('front/images/bicycle.png') }}" alt=""></li>
                                <li class="offers_icons_item"><img src="{{ asset('front/images/sailboat.png') }}" alt=""></li>
                            </ul>
                        </div>
                        <div class="button book_button"><a href="#">View More<span></span><span></span><span></span></a></div>

                    </div>
                </div>
            </div>
            <div align="center" height="100" weight="100">     <a href="{{ url('edit_reservation' , {id : v.id} )}}"><button type="button" class="btn btn-info mb-4" name="button"> Modifier </button> </a></div>
        </div>
    {% endfor %}

{% endblock %}

templates/reservation/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}  Reservations {% endblock %}

{% block content %}
<h1 class='text-center'>Gestion des Reservations</h1>

<body id="page-top">
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-body">
        <div>
        <a href="{{ url('reservation_new')}}"><button type="button" class="btn btn-info mb-4" name="button"> Ajouter </button> </a>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Date reservation</th>
                    <th>Tarif</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                </tr>
                </thead>
                <tbody>
                {% for reservation in reservations %}
                    <tr>
                        <td>{{ reservation.id }}</td>
                        <td>{{ reservation.dateReservation ? reservation.dateReservation|date('Y-m-d') : '' }}</td>
                        <td>{{ reservation.tarif }}</td>
                        <td> <a href="{{ url('reservation_edit' , {id : reservation.id} ) }}"> <img src="{{ asset('back/img/edit.png') }}" alt="edit" width="50px" height="50px" >  </a> </td>
                        <td><a href="{{ url('reservation_delete' , {id : reservation.id} ) }}"> <img src="{{ asset('back/img/icon-delete.jpg') }}" alt="edit" width="50px" height="50px" >  </a></td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>





{% endblock %}

templates/reservation/show.html.twig
<!DOCTYPE html>

<title>Reservation</title>

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Date_reservation</th>
                <td>{{ reservation.dateReservation ? reservation.dateReservation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Tarif</th>
                <td>{{ reservation.tarif }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservation_index') }}">back to list</a>

    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}