src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=PromotionRepository::class)
 */
class Promotion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $nom;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank
     */
    private $date_fin;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank
     */
    private $pourcentage;

    /**
     * @ORM\ManyToOne(targetEntity=Hotel::class, inversedBy="promotions")
     * @ORM\JoinColumn(nullable=true,onDelete="CASCADE")
     */
    private $hotel;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="promotions")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getPourcentage(): ?float
    {
        return $this->pourcentage;
    }

    public function setPourcentage(?float $pourcentage): self
    {
        $this->pourcentage = $pourcentage;

        return $this;
    }

    public function getHotel(): ?Hotel
    {
        return $this->hotel;
    }

    public function setHotel(?Hotel $hotel): self
    {
        $this->hotel = $hotel;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/PromotionType.php
<?php

namespace App\Form;

use App\Entity\Promotion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('date_debut')
            ->add('date_fin')
            ->add('pourcentage')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Hotel;
use App\Entity\Promotion;
use App\Entity\Reclamation;
use App\Entity\User;
use App\Form\PromotionType;
use App\Repository\PromotionRepository;
use App\Repository\ReclamationRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;


class PromotionController extends AbstractController
{
    /**
     * @Route("/promotion", name="promotion_index", methods={"GET"})
     */
    public function index(PromotionRepository $promotionRepository): Response
    {

        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}/newpromotion", name="promotion_new", methods={"GET","POST"})
     */
    public function new(Request $request,$id,SessionInterface $session): Response
    {
        if (!$session->has("user"))
        {
            return $this->redirectToRoute("login");
        }

        if ($session->get("user")->getRoles()[0] == "ROLE_TOURIST")
        {
            return $this->redirectToRoute("fronthome");
        }
        $promotion = new Promotion();
        $form = $this->createForm(PromotionType::class, $promotion)
            ->add("ajouter", SubmitType::class);
        $hotelRep = $this->getDoctrine()->getRepository(Hotel::class);
        $hotel = $hotelRep->find($id);
        if ($hotel == null) {
            return $this->redirectToRoute('fronthome');
        } else {

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {

                $userRep = $this->getDoctrine()->getRepository(User::class);
                $user = $userRep->find($session->get('user'));
                $promotion->setHotel($hotel);
                $promotion->setUser($user);
                    if (($promotion->getDateDebut() < new \DateTime()) or (($promotion->getDateDebut() > $promotion->getDateFin()))) {
                    return $this->render('promotion/new.html.twig', [
                        'promotion' => $promotion,
                        'form' => $form->createView(),
                        'check' => true
                    ]);
                } else {

                    $entityManager = $this->getDoctrine()->getManager();
                    $entityManager->persist($promotion);
                    $entityManager->flush();

                    return $this->redirectToRoute('listerpro');
                }
            }
            return $this->render('promotion/new.html.twig', [
                'promotion' => $promotion,
                'form' => $form->createView(),
            ]);

        }
    }

    /**
     * @Route("/{id}/showpromotion", name="promotion_show", methods={"GET"})
     */
    public function show(Promotion $promotion): Response
    {
        return $this->render('promotion/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    /**
     * @Route("/{id}/editpromotion", name="promotion_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Promotion $promotion): Response
    {
        $form = $this->createForm(PromotionType::class, $promotion)
            ->add("modifier",SubmitType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (($promotion->getDateDebut() < new \DateTime()) or (($promotion->getDateDebut() > $promotion->getDateFin()))) {
                return $this->render('promotion/edit.html.twig', [
                    'promotion' => $promotion,
                    'form' => $form->createView(),
                    'check' => true
                ]);
            } else {

                $this->getDoctrine()->getManager()->flush();

                return $this->redirectToRoute('listerpro');
            }}

        return $this->render('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form->createView(),
        ]);
    }



    /**
     * @Route("/{id}/deletepromotion", name="promotion_delete")
     */
    public function delete(Request $request, $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $promoRepository = $this->getDoctrine()->getRepository(Promotion::class);
        $promotion = $promoRepository->find($id);
        $entityManager->remove($promotion);
        $entityManager->flush();
        return $this->redirectToRoute('listerpro');
    }

    /**
     * @Route("/{id}/deletepromotionback", name="promotion_deleteback")
     */
    public function deleteback(Request $request, $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $promoRepository = $this->getDoctrine()->getRepository(Promotion::class);
        $promotion = $promoRepository->find($id);
        $entityManager->remove($promotion);
        $entityManager->flush();
        return $this->redirectToRoute('promotion_index');
    }


    /**
     * @Route("/listerpro", name="listerpro", methods={"GET"})
     */
    public function lister(PromotionRepository $promotionRepository,PaginatorInterface $paginator,Request $request, SessionInterface $session)
    {
        if (!$session->has("user"))
        {
            return $this->redirectToRoute("login");
        }
        $userRep = $this->getDoctrine()->getRepository(User::class);
        $user = $userRep->find($session->get('user'));
        $promotion = $promotionRepository->findByUser($user);
        $evenements = $paginator->paginate(
            $promotion ,
            $request->query->getInt('page',1),
            2
        );
        return $this->render('/promotion/mespromo.html.twig',
            ['listepro' => $evenements]);


    }


    public function getStatDate($data)
    {
        $res = array(0,0,0,0,0,0,0,0,0,0,0,0) ;
        foreach ($data as $r)
        {

            $index = $r->getDateDebut()->format('m') ;
            if ((int)$index >= 10)
                $index = $r->getDateDebut()->format('m') - 1 ;
            else
                $index = $r->getDateDebut()->format('m')[1] - 1 ;
            $res[$index]++ ;
        }

        return $res ;
    }


    /**
     * @Route("/statpro", name="statpro", methods={"GET"})
     */
    public function stat(PromotionRepository $promotionRepository)
    {

        $data=$promotionRepository->findAll();
        $res = $this->getStatDate($data) ;

        return $this->render('/promotion/statpro.html.twig' ,['res'=>$res]

        );
    }
}

templates/promotion/_delete_form.html.twig
<form method="post" action="{{ path('promotion_delete', {'id': promotion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/promotion/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/promotion/edit.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %}  promotion {% endblock %}
{% block  search%}{% endblock %}
{% block change %}



    <!-- Contact -->

    <div class="contact_form_section" style="margin: 50px">
        <div class="container">
            <div class="row">
                <div class="col">

                    <!-- Contact Form -->
                    <div class="contact_form_container">
                        <div class="contact_title text-center">Edit Promotion</div>


                        <div>
                            <div class="form-group">
                                {{ form_start(form) }}
                                {{ form_label(form.nom) }}
                                {{ form_widget(form.nom , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Name'}} ) }}
                                {{ form_errors(form.nom) }}
                            </div>
                            <div class="form-group">
                                {{ form_label(form.date_debut) }}

                                {{ form_widget(form.date_debut , {'attr': {'class': ' form-select-lg form-control form-control-user' , 'placeholder' : 'Date Debut'}} ) }}
                                {{ form_errors(form.date_debut) }}
                            </div>
                            <div class="form-group">
                                {{ form_label(form.date_fin) }}

                                {{ form_widget(form.date_fin , {'attr': {'class': ' form-select-lg form-control form-control-user' , 'style':'width:100'}} ) }}
                                {{ form_errors(form.date_fin) }}
                            </div>

                            <div class="form-group">
                                {{ form_label(form.pourcentage) }}
                                {{ form_widget(form.pourcentage , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Pourcentage'}} ) }}
                                {{ form_errors(form.pourcentage) }}
                            </div>
                            {{ form_widget(form.modifier ,{'attr': {'class': 'btn btn-block btn-warning' }}) }}
                            {{ form_end(form) }}

                            {% if check is defined %}
                                check date
                            {% endif %}
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/promotion/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}  Promotion {% endblock %}

{% block content %}

    <h1 style="text-align: center">Liste de Promotion </h1>
    <input class="form-control" id="myInput" type="text" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">


    <div class="card shadow mb-4">
        <div class="card-body">

            <div class="table-responsive">
                <table class="table table-bordered" id="hi" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nom</th>
                        <th>Date_debut</th>
                        <th>Date_fin</th>
                        <th>Pourcentage</th>
                        <th>actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for promotion in promotions %}
                        <tr>
                            <td>{{ promotion.id }}</td>
                            <td>{{ promotion.nom }}</td>
                            <td>{{ promotion.dateDebut ? promotion.dateDebut|date('Y-m-d') : '' }}</td>
                            <td>{{ promotion.dateFin ? promotion.dateFin|date('Y-m-d') : '' }}</td>
                            <td>{{ promotion.pourcentage }}</td>

                            <td>
                                <a href="{{ url('promotion_deleteback' , {id : promotion.id} ) }}"> <img src="{{ asset('back/img/icon-delete.jpg') }}" alt="edit" width="50px" height="50px" >  </a>
                            </td>

                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="6">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#hi tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>


{% endblock %}

templates/promotion/mespromo.html.twig
{% block up %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Travelix Project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{asset('front/styles/bootstrap4/bootstrap.min.css')}}">
    <link href="{{asset('front/plugins/font-awesome-4.7.0/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{{asset('front/plugins/OwlCarousel2-2.2.1/owl.carousel.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('front/plugins/OwlCarousel2-2.2.1/owl.theme.default.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('front/plugins/OwlCarousel2-2.2.1/animate.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('front/styles/main_styles.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('front/styles/responsive.css')}}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<style>

    .btn-group .btn {
        transition: background-color .3s ease;
    }

    .panel-table .panel-body {
        padding: 0;
    }

    .table > thead > tr > th {
        border-bottom: none;
    }

    .panel-footer, .panel-table .panel-body .table-bordered {
        border-style: none;
        margin: 0;
    }

    .panel-table .panel-body .table-bordered > thead > tr > th:first-of-type {
        text-align: center;
        width: 50px;
    }

    .panel-table .panel-body .table-bordered > thead > tr > th.col-tools {
        text-align: center;
        width: 120px;
    }

    .panel-table .panel-body .table-bordered > thead > tr > th:last-of-type,
    .panel-table .panel-body .table-bordered > tbody > tr > td:last-of-type {
        border-right: 0;
    }

    .panel-table .panel-body .table-bordered > thead > tr > th:first-of-type,
    .panel-table .panel-body .table-bordered > tbody > tr > td:first-of-type {
        border-left: 0;
    }

    .panel-table .panel-body .table-bordered > tbody > tr:first-of-type > td {
        border-bottom: 0;
    }

    .panel-table .panel-body .table-bordered > thead > tr:first-of-type > th {
        border-top: 0;
    }

    .pagination > li > a, .pagination > li > span {
        border-radius: 50% !important;
        margin: 0 5px;
    }

    .pagination {
        margin: 0;
    }
</style>
{% endblock %}


{% extends 'baseFront.html.twig' %}

{% block title %}  reclamation {% endblock %}
{% block search %}
{% endblock %}
{% block change %}
    <div class="container" style="padding: 10px">
        <div class="card">
            <table class="table table-hover shopping-cart-wrap">
                <thead class="text-muted">
                <tr>
                    <th scope="col">Promotion</th>
                    <th scope="col" width="120">Pourcentage</th>
                    <th scope="col" width="200" class="text-right" align="center">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for promotion in listepro %}
                <tr>
                    <td>
                        <figure class="media" >
                            <div class="img-wrap"><img src={{ asset("upload/"~promotion.hotel.image) }}
                                                       class="img-thumbnail img-sm" width="200px" height="300px" ></div>
                            <figcaption class="media-body"  >
                                <h6 class="title text-truncate">{{ promotion.nom}} </h6>
                                <dl class="param param-inline small">
                                    <dt>Hotel: </dt>
                                    <dd>{{ promotion.hotel }}</dd>
                                </dl>
                                <dl class="param param-inline small">
                                    <dt>Date: </dt>
                                    <dd> {{ promotion.dateDebut|date('Y-m-d') }} --> {{ promotion.dateFin|date('Y-m-d') }}</dd>
                                </dl>
                            </figcaption>
                        </figure>
                    </td>
                    <td>

                        <div class="progress">
                            <div style="width: {{ promotion.pourcentage }}%;" aria-valuemax="100" aria-valuemin="0"
                                  role="progressbar" class="green progress-bar">
                                <span>{{ promotion.pourcentage }}%</span>
                            </div>
                        </div>

                        <div class="price-wrap">
                            {% set p =(promotion.hotel.prix)-( (promotion.hotel.prix) * (promotion.pourcentage/100)) %}
                            <var class="price">{{ p }} DT </var>
                            <small class="text-muted"><del>{{ promotion.hotel.prix }}DT</del></small>
                        </div>
                    </td>
                    <td style="text-align: right">
                        <a class="btn btn-default"  href="{{ url('promotion_edit', {'id': promotion.id}) }}"><span class="glyphicon glyphicon-pencil"
                                                         aria-hidden="true"></span></a>
                        <a class="btn btn-danger" href="{{ url('promotion_delete', {'id': promotion.id}) }}"><span class="glyphicon glyphicon-trash"
                                                        aria-hidden="true"></span></a>
                    </td>

                {% endfor %}
                </tbody>
            </table>
        </div> <!-- card.// -->

    </div>

{% endblock %}

templates/promotion/new.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %}  reclamation {% endblock %}

{% block search %} {% endblock %}

{% block change %}



<!-- Contact -->

<div class="contact_form_section" style="margin: 50px">
    <div class="container">
        <div class="row">
            <div class="col">

                <!-- Contact Form -->
                <div class="contact_form_container">
                <div class="contact_title text-center">Ajouter Promotion</div>


<div>
    <div class="form-group">
        {{ form_start(form) }}
        {{ form_label(form.nom) }}
        {{ form_widget(form.nom , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Name'}} ) }}
        {{ form_errors(form.nom) }}
    </div>
    <div class="form-group">
        {{ form_label(form.date_debut) }}

        {{ form_widget(form.date_debut , {'attr': {'class': ' form-select-lg form-control form-control-user' , 'placeholder' : 'Date Debut'}} ) }}
        {{ form_errors(form.date_debut) }}
    </div>
    <div class="form-group">
        {{ form_label(form.date_fin) }}

        {{ form_widget(form.date_fin , {'attr': {'class': ' form-select-lg form-control form-control-user' , 'style':'width:100'}} ) }}
        {{ form_errors(form.date_fin) }}
    </div>

    <div class="form-group">
        {{ form_label(form.pourcentage) }}
        {{ form_widget(form.pourcentage , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Pourcentage'}} ) }}
        {{ form_errors(form.pourcentage) }}
    </div>
    {{ form_widget(form.ajouter,{'attr': {'class': 'btn btn-block btn-warning'}} ) }}
    {{ form_end(form) }}

    {% if check is defined %}
    check date
    {% endif %}
</div>


                </div>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/promotion/show.html.twig
<!DOCTYPE html>

<title>Promotion</title>

{% block body %}
    <h1>Promotion</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ promotion.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ promotion.nom }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ promotion.dateDebut ? promotion.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ promotion.dateFin ? promotion.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Pourcentage</th>
                <td>{{ promotion.pourcentage }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('promotion_index') }}">back to list</a>

    <a href="{{ path('promotion_edit', {'id': promotion.id}) }}">edit</a>

    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}